context:
  version: 0.2.1
  r_version: 4.3
package:
  name: r-serum-ig-pipeline-code
  version: ${{ version }}
source:
  url: https://github.com/twillis209/serumIgPipelineCode/releases/download/v${{ version
    }}/serumIgPipelineCode_${{ version }}.tar.gz
  sha256: 0b9c845f8158e80e974f8a3aea40e954157c7143f81fb9ef19cd684ba225b8b6
build:
  script: R CMD INSTALL --build .
requirements:
  host:
  - r-base >= ${{ r_version }}
  - r-data.table (>= 1.15)
  - r-dplyr
  - r-ggplot2
  - r-ggtext
  - r-magrittr
  - r-scales
  run:
  - r-base
  - r-data.table (>= 1.15)
  - r-dplyr
  - r-ggplot2
  - r-ggtext
  - r-magrittr
  - r-scales
tests:
- script:
  # TODO I get a warning about the package not being installed from testthat: No installed testthat tests found for serumIgPipelineCode
  # TODO fix is apparently to put tests in inst, not sure how to automate this
  - Rscript -e "library('serumIgPipelineCode');"
  - Rscript -e "library(serumIgPipelineCode); testthat::test_package('serumIgPipelineCode')"
  requirements:
    run: 
    - r-testthat
about:
  homepage: https://github.com/twillis209/serumIgPipelineCode
  summary: Ancillary code for the serum Ig paper pipeline
  description: This package contains R code used to generate the results in the serum
    Ig paper.
  license: MIT
  repository: https://github.com/twillis209/serumIgPipelineCode
