context:
  version: 0.1.0
  r_version: 4.3

package:
  name: serumIgPipelineCode
  version: ${{ version }}

source:
  url: https://github.com/twillis209/serumIgPipelineCode/releases/download/v0.1.0/serumIgPipelineCode_0.1.0.tar.gz
  sha256: 902655c5dcbfc6f726578981642c19b926bfb30fef2542c96ec1e7ed23e8652d

build:
  script: R CMD INSTALL --build .

requirements:
  host:
  - r-base >= ${{ r_version }}
  - r-data.table >= 1.15
  run:
  - r-base >= ${{ r_version }}
  - r-data.table >= 1.15

#tests:
#  - script:
#    - Rscript -e "library(serumIgPipelineCode)"

about:
  homepage: https://github.com/twillis209/serumIgPipelineCode
  summary: "Ancillary code for the serum Ig paper pipeline"
  description: |-
    This package contains R code used to generate the results in the serum Ig paper.
  license: MIT
  repository: https://github.com/twillis209/serumIgPipelineCode